#Deploy the pod
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: stock-quote
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: stock-quote
    spec:
      containers:
      - name: stock-quote
        image: kyleschlosser/stock-quote:redis
        ports:
          - containerPort: 9080
        imagePullPolicy: Always
      imagePullSecrets:
      - name: dockerhubsecret
---
#Deploy the service
apiVersion: v1
kind: Service
metadata:
  name: stock-quote-service
  labels:
    app: stock-quote
spec:
  type: NodePort
  ports:
    - port: 9080
      nodePort: 31002
  selector:
    app: stock-quote
---   
#Configure the ingress 
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
# annotations:
#   ingress.kubernetes.io/rewrite-target: /stock-quote
  name: stock-quote-ingress
spec:
  rules:
  - http:
      paths:
      - path: /stock-quote
        backend:
          serviceName: stock-quote-service
          servicePort: 9080
